#!/usr/bin/env ruby

require_relative "../lib/rails_grpc/cli"

begin
  cli = RailsGrpc::CLI.instance
  cli.parse
  cli.run
rescue => e
  STDERR.puts e.message
  STDERR.puts e.backtrace.join("\n")
  exit 1
end
